version: "3.8"
services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    restart: on-failure
    # environment:
    # - RABBITMQ_DEFAULT_USER=myuser
    # - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3

  producer:
    restart: on-failure
    build: producer
    ports:
      - '3000:3000'
    environment:
      AMQP_URL: 'amqp://@rabbitmq3:5672'
    depends_on:
      - rabbitmq3

  consumer:
    restart: on-failure
    build: consumer
    environment:
      AMQP_URL: 'amqp://@rabbitmq3:5672'
    depends_on:
      - rabbitmq3

volumes:
  rabbitmq-data:
