name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [16.x]
        path: [producer, consumer]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
        working-directory: ${{ env.working-directory }}
      - run: ls -la
        working-directory: ${{ env.working-directory }}
      - run: yarn --frozen-lockfile
        working-directory: ${{ env.working-directory }}
      - run: yarn build
        working-directory: ${{ env.working-directory }}
      - run: yarn lint
        working-directory: ${{ env.working-directory }}
      # - run: yarn test
      # - name: Upload coverage reports to Codecov
      # uses: codecov/codecov-action@v3
  